import { StateContext } from '@/context/stateContext';
import { useContext, useEffect } from 'react';

export default function InvoiceNumberField() {
  const stateContext = useContext(StateContext);
  const { masterState, setMasterState } = stateContext;
  const { invoiceNumber } = masterState.invoice.invoiceInformation;
  const { autoGeneratedInvoiceNumber } = masterState;

  useEffect(() => {
    if (invoiceNumber === '' || invoiceNumber === undefined) {
      setMasterState({
        ...masterState,
        invoice: {
          ...masterState.invoice,
          invoiceInformation: {
            ...masterState.invoice.invoiceInformation,
            invoiceNumber: autoGeneratedInvoiceNumber,
          },
        },
      });
    }
  }, []);

  const updateInvoiceNumber = (e: any) => {
    setMasterState({
      ...masterState,
      invoice: {
        ...masterState.invoice,
        invoiceInformation: {
          ...masterState.invoice.invoiceInformation,
          invoiceNumber: e.target.value,
        },
      },
    });
  };

  return (
    <div>
      <input
        type="text"
        name="text"
        id="email"
        className="text-md block w-full max-w-[80px] rounded-md border-0 py-1.5 font-medium text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:leading-6"
        onChange={(e) => updateInvoiceNumber(e)}
        value={invoiceNumber}
      />
    </div>
  );
}
